#!/bin/bash

#this will work currently for paste, but if you change it to adiffrent order (like red blue orange green) it messes it up
#nvm fixed it
color=(blue green orange red)
animals=(fox bear dog moose duck)




srtsys () {

value=("$@")
counter=0
cat $a $b $c > "$counter hold"

for i in ${value[@]}; do
	
	cat $a $b $c | grep $i | cat > $i
	cat "$counter hold" | grep -v $i | cat > "$[$counter + 1] hold"
	rm "$counter hold"
	counter=$[$counter + 1]
	
	
	
done


cat "$counter hold" > other


return
}





srtslct(){

value=("$@")
num=0
for i in ${value[@]}; do
	
	echo " $num . $i"
	num=$(($num + 1))
done

echo " $num . others"
return
}




#insert simple menu here
simplemenudec () {
		
value=("$@")

echo -n "which of the following selection would you like? 0-${#value[@]}"
read REPLY

num_of_optn=$((${#value[@]}-1))


if [[ $REPLY =~ ^[0-$num_of_optn]$ ]]; then
	
	cat $a $b $c | grep ${value[$REPLY]} | cat > New_file
	
elif [[ $REPLY == ${#value[@]} ]]; then
	cat other > New_file
	
else
	echo "invalid, cant you read?" >&2
	exit 1
fi



echo "the selection have ven isolated to new_file"
	gedit New_file

return
}





echo "animalsort is here to try and sort animals and things into diffrenct catagories currently designed for 3 files at once

"

echo "enter the files to be used==>: "
read a b c



printf "%s	%s	%s \n--------------------------------------------- \n" $a $b $c
#you dont actully need the -d and the giant space
echo "$(paste -d '	' $a $b $c)"

echo -n "

select you preferred sorting system

1. color
2. species

"
read REPLY

if [[ $REPLY =~ ^[1-2]$ ]]; then
	if [[ $REPLY == 1 ]]; then
		srtsys "${color[@]}"
		#my current understanding of past in it's relation to forming columns is poor. It's very possible that i will change it, change 		it to a non txt file format and fuck it all up :(
		#woo i did it!!
		paste "${color[@]}" other | expand -t 15
		rm ${color[@]}
		
		srtslct "${color[@]}"
		simplemenudec "${color[@]}"
		exit
	fi
	if [[ $REPLY == 2 ]]; then
		srtsys "${animals[@]}"
		paste "${animals[@]}" other | expand -t 15
		rm ${animals[@]}
		
		srtslct "${animals[@]}"
		simplemenudec "${animals[@]}"
		exit
	fi
	
else
	echo "invalid, cant you read?" >&2
	exit 1
fi



# can be made mre complex, with "intellignet" sorting according to what's displayed


