#!/bin/bash

#this will work currently for paste, but if you change it to adiffrent order (like red blue orange green) it messes it up
color=(blue green orange red)



srtsys () {
#im pretty sure i went wrong somewhere here? im suppose to use 
# value=$@ but it works anyway
value=$1
for i in ${value[@]}; do
	cat $a $b $c | grep $i | cat > i
done

return
}




srtslct(){

value=$@
num=0
for i in ${value[@]}; do
	echo " $num . $i"
	num=$(($num + 1))
done

return
}




#insert simple menu here
simplemenudec () {
		
value=("$@")

echo -n "which of the following selection would you like? 0-$((${#color[@]}-1))"
read REPLY



if [[ $REPLY =~ ^[0-${#value[@]}]$ ]]; then
	cat $a $b $c | grep ${value[$REPLY]} | cat > New_file
	echo "the selection have ven isolated to new_file"
	gedit New_file
	
	
else
	echo "invalid, cant you read?" >&2
	exit 1
fi
return
}





echo "animalsort is here to try and sort animals and things into diffrenct catagories currently designed for 3 files at once

"

echo "enter the files to be used==>: "
read a b c



printf "%s	%s	%s \n--------------------------------------------- \n" $a $b $c
#you dont actully need the -d and the giant space
echo "$(paste -d '	' $a $b $c)"

echo -n "

select you preferred sorting system

1. color
2. species

"
read REPLY

if [[ $REPLY =~ ^[1-2]$ ]]; then
	if [[ $REPLY == 1 ]]; then
		srtsys "${color[@]}"
		#my current understanding of past in it's relation to forming columns is poor. It's very possible that i will change it, change 		it to a non txt file format and fuck it all up :(
		#woo i did it!!
		paste "${color[@]}" | expand -t 20
		echo ${color[@]}
		
		srtslct "${color[@]}"
		simplemenudec "${color[@]}"
		exit
	fi
	if [[ $REPLY == 2 ]]; then
		echo "	NOT READY YET!!!"
		exit
	fi
	
else
	echo "invalid, cant you read?" >&2
	exit 1
fi



# can be made mre complex, with "intellignet" sorting according to what's displayed


